version: '3'
services:
  
  app:
    build: app
    privileged: true
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
    environment:
      - VERSION=0.9
      - DEBUG=true
      - DB_PATH=/tmp/sensors.db
    volumes:
      - ./sensors.db:/tmp/sensors.db
    ports:
      - "8080:8080"
