version: '3'
services:
  
  app:
    build: app
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
    environment:
      - VERSION=0.9
      - DEBUG=true
    volumes:
      - db:/usr/app/src/db
    ports:
      - "8080:8080"
