version: '3'
services:
  
  app:
    build:
      context: app
      dockerfile: Dockerfile.x86
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --reload
      - --port
      - "8080"
    environment:
      - VERSION=0.9
      - DEBUG=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/app/src

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./templates/dashboard.html:/usr/share/nginx/html/dashboard.html:ro
      - ./templates/index.html:/usr/share/nginx/html/index.html:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro

  grafana:
    image: grafana/grafana-oss:10.1.2
    platform: linux/arm64/v7
    ports:
      - 3000:3000
    volumes:
      - ./app:/tmp