version: '3'
services:
  
  app:
    build: app
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --reload
    environment:
      - VERSION=0.9
      - DEBUG=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/app/src

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./templates/dashboard.html:/usr/share/nginx/html/dashboard.html:ro
      - ./templates/index.html:/usr/share/nginx/html/index.html:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
