version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    network: host

  home:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ./home_assistant_config:/config
      - /run/dbus:/run/dbus:ro
    restart: always
    network: host
